subgroup populations can be provided as a file with flag -S

diff --git a/needLR b/needLR
--- a/needLR
+++ b/needLR
@@ -9,7 +9,8 @@ temp=$(mktemp -u -t needlr.temp.XXXXX)
 
 thisscript=$(realpath "$0")
 scriptpath=${thisscript%/*}
-refloc=REFLOCPATH
+#refloc=REFLOCPATH
+refloc=/home/mgaley/needLR_manu/needLR/backend_files
 FILTERPASS=0 #this setting is to include non-passing variants or not. default is to filter nothing.
 run1kg=1 #this setting determines whether or not to run 1kg specific annotation scripts or use a custom control set
 THREADS=1
@@ -26,6 +27,11 @@ truvari_r=2000
 truvari_p=0
 truvari_P=0.2
 truvari_O=0.2
+
+# other parameters
+
+RUNSUBPOPS=0
+MERGECONTROLS=0
 
 # annotation filenames
 
@@ -97,27 +103,6 @@ INFOCOLTEXT[Allele_Freq_Cohort]='##INFO=<ID=Allele_Freq_Cohort,Number=1,Type=Flo
 INFOCOLTEXT[GT_coh_homWT]='##INFO=<ID=GT_coh_homWT,Number=1,Type=Integer,Description="Count of homozygous genotypes matching the reference in the cohort">'
 INFOCOLTEXT[GT_coh_het]='##INFO=<ID=GT_coh_het,Number=1,Type=Integer,Description="Count of heterozygous genotypes in the cohort">'
 INFOCOLTEXT[GT_coh_homVAR]='##INFO=<ID=GT_coh_homVAR,Number=1,Type=Integer,Description="Count of homozygous genotypes supporting the SV in the cohort">'
-##1kg controls only
-INFOCOLTEXT[Pop_Count_AFR]='##INFO=<ID=Pop_Count_AFR,Number=1,Type=Integer,Description="1KGP AFR samples carrying the SV (n=163)">'
-INFOCOLTEXT[Pop_Freq_AFR]='##INFO=<ID=Pop_Freq_AFR,Number=1,Type=Float,Description="Proportion of 1KGP AFR samples carrying the SV">'
-INFOCOLTEXT[Pop_Count_AMR]='##INFO=<ID=Pop_Count_AMR,Number=1,Type=Integer,Description="1KGP AMR samples carrying the SV (n=67)">'
-INFOCOLTEXT[Pop_Freq_AMR]='##INFO=<ID=Pop_Freq_AMR,Number=1,Type=Float,Description="Proportion of 1KGP AMR samples carrying the SV">'
-INFOCOLTEXT[Pop_Count_EAS]='##INFO=<ID=Pop_Count_EAS,Number=1,Type=Integer,Description="1KGP EAS samples carrying the SV (n=95)">'
-INFOCOLTEXT[Pop_Freq_EAS]='##INFO=<ID=Pop_Freq_EAS,Number=1,Type=Float,Description="Proportion of 1KGP EAS samples carrying the SV">'
-INFOCOLTEXT[Pop_Count_EUR]='##INFO=<ID=Pop_Count_EUR,Number=1,Type=Integer,Description="1KGP EUR samples carrying the SV (n=72)">'
-INFOCOLTEXT[Pop_Freq_EUR]='##INFO=<ID=Pop_Freq_EUR,Number=1,Type=Float,Description="Proportion of 1KGP EUR samples carrying the SV">'
-INFOCOLTEXT[Pop_Count_SAS]='##INFO=<ID=Pop_Count_SAS,Number=1,Type=Integer,Description="1KGP SAS samples carrying the SV (n=103)">'
-INFOCOLTEXT[Pop_Freq_SAS]='##INFO=<ID=Pop_Freq_SAS,Number=1,Type=Float,Description="Proportion of 1KGP SAS samples carrying the SV">'
-INFOCOLTEXT[Allele_Count_AFR]='##INFO=<ID=Allele_Count_AFR,Number=1,Type=Integer,Description="1KGP AFR alleles carrying the SV">'
-INFOCOLTEXT[Allele_Freq_AFR]='##INFO=<ID=Allele_Freq_AFR,Number=1,Type=Float,Description="1KGP AFR allele frequency">'
-INFOCOLTEXT[Allele_Count_AMR]='##INFO=<ID=Allele_Count_AMR,Number=1,Type=Integer,Description="1KGP AMR alleles carrying the SV">'
-INFOCOLTEXT[Allele_Freq_AMR]='##INFO=<ID=Allele_Freq_AMR,Number=1,Type=Float,Description="1KGP AMR allele frequency">'
-INFOCOLTEXT[Allele_Count_EAS]='##INFO=<ID=Allele_Count_EAS,Number=1,Type=Integer,Description="1KGP EAS alleles carrying the SV">'
-INFOCOLTEXT[Allele_Freq_EAS]='##INFO=<ID=Allele_Freq_EAS,Number=1,Type=Float,Description="1KGP EAS allele frequency">'
-INFOCOLTEXT[Allele_Count_EUR]='##INFO=<ID=Allele_Count_EUR,Number=1,Type=Integer,Description="1KGP EUR alleles carrying the SV">'
-INFOCOLTEXT[Allele_Freq_EUR]='##INFO=<ID=Allele_Freq_EUR,Number=1,Type=Float,Description="1KGP EUR allele frequency">'
-INFOCOLTEXT[Allele_Count_SAS]='##INFO=<ID=Allele_Count_SAS,Number=1,Type=Integer,Description="1KGP SAS alleles carrying the SV">'
-INFOCOLTEXT[Allele_Freq_SAS]='##INFO=<ID=Allele_Freq_SAS,Number=1,Type=Float,Description="1KGP SAS allele frequency">'
 ##annotations
 INFOCOLTEXT[OMIM_phenotype]='##INFO=<ID=OMIM_phenotype,Number=.,Type=String,Description="OMIM phenotypes associated with any gene the SV overlaps (OMIM 20260129)">'
 INFOCOLTEXT[OMIM_MOI]='##INFO=<ID=OMIM_MOI,Number=.,Type=String,Description="Mode of inheritance associated with phenotypes and genes the SV overlaps (OMIM 20260129)">'
@@ -225,6 +210,7 @@ annotateHelp() {
     - L     : [ .txt file list of full file paths to gzipped query vcfs ]
     - Q     : [ full path to a truvari-merged query cohort vcf ]
     - O     : [ output directory name (default is needLR_output relative to current directory) ]
+    - S     : [ subpopulation names and counts, provided as a .csv/.tsv file or a , separated list of : pairs ]
 
     General Annotation options:
     --all    :   [ annotate VCF with all available options listed below (default TRUE) ]
@@ -249,8 +235,6 @@ annotateHelp() {
     """
 }
 
-
-
 bedHelp() {
     echo """
     Usage: needLR bed <options> {input}
@@ -265,6 +249,8 @@ bedHelp() {
 
     """
 }
+
+############################# preprocessing and validation functions #######################################################################################
 
 validateVCF () {
     local vcf=$1
@@ -315,6 +301,96 @@ validateVCF () {
     fi
 }
 
+truvari_ctrl_merge () {
+    local ctrl_files=$1
+    local output=$2
+
+    query_list=( $(echo ${ctrl_files} | tr ',' ' ') )
+
+    echo -e "\nMerging Control Sets\n"
+    #output="${UNSOLVED_DIR}/$(basename ${query_file} .vcf.gz).intermediate"
+
+    #This preprocesses the control VCFs to be >=50bp, on full chromosomes, and FILTER=PASS
+    echo "Preprocessing query VCF to SVs >=50bp, on full chromosomes, FILTER=$FILTERPASS"
+    #bcffilters=\''(INFO/SVTYPE="BND") || (INFO/SVTYPE="INS" || INFO/SVTYPE="DEL" || INFO/SVTYPE="DUP" || INFO/SVTYPE="INV") && (INFO/SVLEN > 49 || INFO/SVLEN < -49) && GT!="0/0" && GT!="0|0"'\'
+    chroms="chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chrX,chrY,chrM"
+
+    if [ -f "${temp}.list_temp.txt" ]
+    then
+        rm "${temp}.list_temp.txt"
+    fi
+
+    for((i=0;i<${#query_list[@]};i++))
+    do
+        query_file=${query_list[$i]}
+        currentlines=$( zgrep -v ^# ${query_file} | wc -l | tr -s ' ' | cut -f1 -d ' ')
+        echo "There are $currentlines starting variants in ${query_file}"
+
+        
+        if [ $FILTERPASS -eq 1 ]
+        then
+            bcftools view -f PASS \
+            -i '(INFO/SVTYPE="BND") || (INFO/SVTYPE="INS" || INFO/SVTYPE="DEL" || INFO/SVTYPE="DUP" || INFO/SVTYPE="INV") && (INFO/SVLEN > 49 || INFO/SVLEN < -49) && GT!="0/0" && GT!="0|0"' \
+                -r $chroms \
+                -o ${output}.${i}.filter.vcf.gz \
+                --threads ${THREADS} \
+                --write-index=tbi "${query_file}"
+        else
+            bcftools view -i '(INFO/SVTYPE="BND") || (INFO/SVTYPE="INS" || INFO/SVTYPE="DEL" || INFO/SVTYPE="DUP" || INFO/SVTYPE="INV") && (INFO/SVLEN > 49 || INFO/SVLEN < -49) && GT!="0/0" && GT!="0|0"' \
+                -r $chroms \
+                -o ${output}.${i}.filter.vcf.gz \
+                --threads ${THREADS} \
+                --write-index=tbi "${query_file}"
+        fi
+
+        newlines=$( zgrep -v ^# ${output}.${i}.filter.vcf.gz | wc -l | tr -s ' ' | cut -f1 -d ' ')
+        delta=$(( currentlines-newlines ))
+        echo "Removed $delta lines from ${query_file}"
+        currentlines=$newlines
+
+        echo "${output}.${i}.filter.vcf.gz" >> "${temp}.list_temp.txt" #actually adding to the list inside of the loop
+    done
+
+    #This creates the input list of VCFs for bcftools merge
+    echo "Creating list of input VCFs for bcftools merge"
+    echo "${DATA1KG}" >> "${temp}.list_temp.txt"
+
+    #bcftools merge
+    echo "Merging"
+    bcftools merge -m none \
+        --force-samples \
+        -l "${temp}.list_temp.txt" \
+        -Oz \
+        --threads $THREADS \
+        -o "${output}_bcftools_merged_with_ctrl_temp.vcf.gz" \
+        --write-index=tbi
+
+    newlines=$( zgrep -v ^# ${output}_bcftools_merged_with_ctrl_temp.vcf.gz | wc -l | tr -s ' ' | cut -f1 -d ' ')
+    delta=$(( currentlines-newlines ))
+    echo "Added $delta lines"
+    currentlines=$newlines
+
+    #Truvari collapse (T31)
+    echo "Running truvari collapse"
+    truvari collapse -i "${output}_bcftools_merged_with_ctrl_temp.vcf.gz" \
+        -o "${output}_truvari_merged_temp.vcf" \
+        -c "${output}_truvari_collapsed_temp.vcf" \
+        -k "${truvari_k}" \
+        -s "${truvari_s}" \
+        -S "${truvari_S}" \
+        -r "${truvari_r}" \
+        -p "${truvari_p}" \
+        -P "${truvari_P}" \
+        -O "${truvari_O}"
+
+    bgzip "${output}_truvari_merged_temp.vcf"
+    tabix -p vcf "${output}_truvari_merged_temp.vcf.gz"
+    mv "${output}_truvari_merged_temp.vcf.gz" > "${output}.truvari_merged_controls.vcf.gz"
+
+    echo -e "\nDone\n"
+}
+
+
 ############################# input processing #######################################################################################
 #### get subcommand to run
 
@@ -344,7 +420,7 @@ shift
 alcannotations=""
 
 ### get other flags and options
-while getopts HP:C:L:Q:O:B:T:R:-: option
+while getopts HP:C:L:Q:O:B:T:R:S:-: option
 do
     case "${option}" in
         -)
@@ -354,6 +430,7 @@ do
                 alcannotations+=$alcannotations,$longoption ;;
 
                 all) SELECTEDANNO=$(echo ${ALLANNOTATIONLIST[@]} | tr ' ' ',') ;;
+                keep1kg) MERGECONTROLS=1 ;;
                 *) echo "option $longoption not recognized, ignoring" ;;
             esac ;;
         H) help
@@ -367,6 +444,7 @@ do
         T) THREADS="${OPTARG}" ;;
         F) FILTERPASS=1 ;;
         R) ANALYSISREGION="${OPTARG}" ;;
+        S) SUBPOPS="${OPTARG}" ;;
         
     esac
 done
@@ -481,6 +559,7 @@ else
     done
 fi
 
+
 # check if using an external control set vcf
 if [[ ! -z ${TRUVARI_MERGED_CTRL_SET+x} ]]
 then
@@ -488,20 +567,122 @@ then
     CTRL_MERGED=${TRUVARI_MERGED_CTRL_SET}
     CTRL_SAMPLE_NAME_LIST=( $(bcftools view -h ${CTRL_MERGED} | grep -v ^## | cut -f10-) )
     TOTAL_SAMPLES=${#CTRL_SAMPLE_NAME_LIST[@]}
+
+    # read from either a textfile or the comma and colon separated pairs 
+    if [ ! -z ${SUBPOPS+x} ]
+    then
+        RUNSUBPOPS=1
+        # check if $SUBPOPS is a file
+        if [[ ${SUBPOPS} =~ "tsv" || ${SUBPOPS} =~ "csv" ]]
+        then
+            # read contents of file and then reset subpops and control vcf variables
+            cat ${SUBPOPS} | tr ',' '\t' | sort -k2,2 > $temp.subpop.labels.tsv
+            cut -f1 $temp.subpop.labels.tsv > $temp.subpop.ordered.names.txt
+            labelnames=( $(cut -f2 $temp.subpop.labels.tsv| uniq ) )
+            cut -f2 $temp.subpop.labels.tsv | awk '{subpops[$0]+=1}END{for(i in subpops){print i,subpops[i]}}' > $temp.subpop.unordered.counts.txt
+            subpoplevels=()
+            for label in ${labelnames[@]}
+            do
+                labelcount=$( grep $label $temp.subpop.unordered.counts.txt | cut -d ' ' -f2)
+                subpoplevels+=( "${label}:${labelcount}" )
+            done
+            SUBPOPS=$(echo ${subpoplevels[@]} | tr ' ' ',')
+            echo "sorting samples in control VCF by supopulation"
+            bcftools view --threads ${THREADS} \
+                --samples-file $temp.subpop.ordered.names.txt \
+                --force-samples \
+                -Oz -o $temp.custom_control.reordered.vcf.gz \
+                --write-index=tbi \
+                ${CTRL_MERGED}
+            CTRL_MERGED=$temp.custom_control.reordered.vcf.gz
+        fi
+        #if SUBPOPS is not a file, make sure there are no repeats
+        if [ ${MERGECONTROLS} -eq 0 ]
+        then
+            subgroups=( $(echo ${SUBPOPS} | tr ',' ' ') )
+            SUBGROUP_LABELS=()
+            SUBGROUP_COUNTS=()
+            echo "Subpopulation counts are:"
+            for group in ${subgroups[@]}
+            do
+                grouplabels=( $(echo $group | tr ':' ' ') )
+                SUBGROUP_LABELS+=( ${grouplabels[0]} )
+                SUBGROUP_COUNTS+=( ${grouplabels[1]} )
+                echo "${grouplabels[0]}:${grouplabels[1]}"
+            done
+            NSUBGROUPS=${#SUBGROUP_LABELS[@]}
+            uniquelabels=( $(echo ${SUBGROUP_LABELS[@]} | tr ' ' '\n' | sort | uniq ) )
+            if [[ ${#uniquelabels[@]} -ne ${NSUBGROUPS} ]]
+            then
+                echo "Error: subgroups must be unique"
+                echo "subgroups supplied: ${SUBGROUP_LABELS[@]}"
+                exit 1
+            fi
+        else
+            truvari_ctrl_merge ${CTRL_MERGED} $temp.custom_control
+            CTRL_MERGED=$temp.custom_control.truvari_merged_controls.vcf.gz
+            CTRL_SAMPLE_NAME_LIST=( $(bcftools view -h ${CTRL_MERGED} | grep -v ^## | cut -f10-) )
+            TOTAL_SAMPLES=${#CTRL_SAMPLE_NAME_LIST[@]}
+
+            subgroups=( $(echo ${SUBPOPS} | tr ',' ' ') )
+            SUBGROUP_LABELS=()
+            SUBGROUP_COUNTS=()
+            echo "Subpopulation counts are:"
+            for group in ${subgroups[@]}
+            do
+                grouplabels=( $(echo $group | tr ':' ' ') )
+                SUBGROUP_LABELS+=( ${grouplabels[0]} )
+                SUBGROUP_COUNTS+=( ${grouplabels[1]} )
+                echo "${grouplabels[0]}:${grouplabels[1]}"
+            done
+            LABELS_1KG=( AFR AMR EAS EUR SAS )
+            SAMPLE_NAMES_1KG=( $(bcftools view -h ${DATA1KG} | grep -v ^## | cut -f10-) )
+            for label in ${LABELS_1KG[@]}
+            do
+                count=( $(echo ${SAMPLE_NAMES_1KG} | tr ' ' '\n' | grep -c $label) )
+                SUBGROUP_COUNTS+=( $count )
+                SUBGROUP_LABELS+=( $label )
+                echo "${label}:$count (1kg)"
+            done
+            NSUBGROUPS=${#SUBGROUP_LABELS[@]}
+        fi
+    else
+       NSUBGROUPS=0 
+    fi
 else
     #This is the Truvari merge of 500 1KGP samples
-    CTRL_MERGED="$DATA1KG"
+    CTRL_MERGED="${DATA1KG}"
     
     ##This is the list of the 1KGP sample names in the order they will be merged in Truvari
     CTRL_SAMPLE_NAME_LIST=( $(bcftools view -h ${CTRL_MERGED} | grep -v ^## | cut -f10-) )
     TOTAL_SAMPLES=${#CTRL_SAMPLE_NAME_LIST[@]}
-    AFR=$( echo ${CTRL_SAMPLE_NAME_LIST[@]} | tr ' ' '\n' | grep -c AFR )
-    AMR=$( echo ${CTRL_SAMPLE_NAME_LIST[@]} | tr ' ' '\n' | grep -c AMR )
-    EAS=$( echo ${CTRL_SAMPLE_NAME_LIST[@]} | tr ' ' '\n' | grep -c EAS )
-    EUR=$( echo ${CTRL_SAMPLE_NAME_LIST[@]} | tr ' ' '\n' | grep -c EUR )
-    SAS=$( echo ${CTRL_SAMPLE_NAME_LIST[@]} | tr ' ' '\n' | grep -c SAS )
-    NSUBGROUPS=6
+    SUBGROUP_LABELS=( AFR AMR EAS EUR SAS )
+    SUBGROUP_COUNTS=()
+    echo "Subpopulation counts are:"
+    for label in ${SUBGROUP_LABELS[@]}
+    do
+        count=$(echo ${CTRL_SAMPLE_NAME_LIST[@]} | tr ' ' '\n' | grep -c $label)
+        SUBGROUP_COUNTS+=( $count )
+        echo "${label}:$count (1kg built in)"
+    done
+    NSUBGROUPS=${#SUBGROUP_LABELS[@]}
+    RUNSUBPOPS=1
 fi
+
+## add infocol text based on subgroups.
+if [[ ${NSUBGROUPS} -gt 0 ]]
+then
+    for((i=0;i<${#SUBGROUP_LABELS[@]};i++))
+    do
+        subgroup=${SUBGROUP_LABELS[$i]}
+        subcount=${SUBGROUP_COUNTS[$i]}
+        INFOCOLTEXT["Pop_Count_${subgroup}"]='##INFO=<ID=Pop_Count_'"${subgroup}"',Number=1,Type=Integer,Description="Control '"${subgroup}"' samples carrying the SV (n='"${subcount}"')">'
+        INFOCOLTEXT["Pop_Freq_${subgroup}"]='##INFO=<ID=Pop_Freq_'"${subgroup}"',Number=1,Type=Float,Description="Proportion of control '"${subgroup}"' samples carrying the SV">'
+        INFOCOLTEXT["Allele_Count_${subgroup}"]='##INFO=<ID=Allele_Count_'"${subgroup}"',Number=1,Type=Integer,Description="Control '"${subgroup}"' alleles carrying the SV">'
+        INFOCOLTEXT["Allele_Freq_${subgroup}"]='##INFO=<ID=Allele_Freq_'"${subgroup}"',Number=1,Type=Float,Description="Control '"${subgroup}"' sallele frequency">'
+    done
+fi
+
 
 # from here options may only be necessary within each command.
 # echo what options have already been processed
@@ -519,6 +700,8 @@ echo """Command         :   needLR $subcommand
 
 ############################# main functions #######################################################################################
 ############ core ##################
+
+
 
 truvari_merge () {
     local query_files=$1
@@ -772,18 +955,18 @@ make_supp_vecc() {
 
     ## Calculate population stratified frequency statistics
     ## this version of the awk script can accept any breaks, not implemented yet for anything but 1kg
-    if [[ $run1kg -eq 1 ]]
+    if [[ $RUNSUBPOPS -eq 1 ]]
     then
-        breaks="$AFR,$AMR,$EAS,$EUR,$SAS"
-        echo "using subpopulation breaks: $breaks"
+        subpopcounts=$(echo ${SUBGROUP_COUNTS[@]} | tr ' ' ',')
+        echo "using subpopulation breaks: $subpopcounts"
     else
-        breaks="${TOTAL_SAMPLES}"
+        subpopcounts="${TOTAL_SAMPLES}"
         echo "no subpopulation breaks provided"
     fi
 
     echo "calculating population stratified frequency statistics"
     cat "${output}_temp5.txt" | $scriptpath/src/./annocustomcontrol.awk \
-        --assign controlbreaks=$breaks \
+        --assign controlbreaks=$subpopcounts \
         --assign ncohort=$nquery \
         --assign ncontrols="${TOTAL_SAMPLES}" \
         --assign step=$querycols > "${output}_temp6.txt"
@@ -844,9 +1027,9 @@ hwe() {
 
     #This lists all population counts/frequencies, allele counts/frequencies, and HWE info
     echo "Tabulating subpopulation and population count/frequencies"
-    if [[ "${run1kg}" -eq 1 ]]
+    if [[ "${RUNSUBPOPS}" -eq 1 ]]
     then
-        subpopcounts="${AFR},${AMR},${EAS},${EUR},${SAS}"
+        subpopcounts=$(echo ${SUBGROUP_COUNTS[@]} | tr ' ' ',')
     else
         subpopcounts="${TOTAL_SAMPLES}"
     fi
@@ -1338,23 +1521,24 @@ printTable() {
 
     let controlstart=$sampleend+1
     let controlend=controlstart
-    if [[ $run1kg -eq 1 ]] #this should be replaced with optional subpopulation names in a later release
+    if [[ $NSUBGROUPS -gt 1 ]] #this should be replaced with optional subpopulation names in a later release
     then
-        tableheader+=(  Pop_Count_AFR Pop_Freq_AFR
-                        Pop_Count_AMR Pop_Freq_AMR 
-                        Pop_Count_EAS Pop_Freq_EAS
-                        Pop_Count_EUR Pop_Freq_EUR
-                        Pop_Count_SAS Pop_Freq_SAS
+        poplabels=()
+        allelelabels=()
+        for subgroup in ${SUBGROUP_LABELS[@]}
+        do
+            poplabels+=( "Pop_Count_${subgroup}" "Pop_Freq_${subgroup}")
+            allelelabels+=( "Allele_Count_${subgroup}" "Allele_Freq_${subgroup}")
+        done
+        tableheader+=(  ${poplabels[@]}
                         Pop_Count_ALL Pop_Freq_ALL 
-                        Allele_Count_AFR Allele_Freq_AFR
-                        Allele_Count_AMR Allele_Freq_AMR 
-                        Allele_Count_EAS Allele_Freq_EAS
-                        Allele_Count_EUR Allele_Freq_EUR
-                        Allele_Count_SAS Allele_Freq_SAS
+                        ${allelelabels[@]}
                         Allele_Count_ALL Allele_Freq_ALL )
-        let controlend=$controlstart+24-1
+
+        let controlend=$controlstart+${#poplabels[@]}+${#allelelabels[@]}+3
         afcol=$controlend
     else
+        echo "no subgroups"
         tableheader+=( Pop_Count_ALL Pop_Freq_ALL Allele_Count_ALL Allele_Freq_ALL )
         let controlend=$controlstart+3
         afcol=$controlend
@@ -1380,8 +1564,9 @@ printTable() {
     longcols=( 4 5 ) #REF ALT
     let annotationstart=$sampleend+2
     NF=$( head -n1 ${output}_results_long.txt | awk '{print NF}' )
-    let SUBGROUPCOLUMNS=${NSUBGROUPS}*4
+    SUBGROUPCOLUMNS=$(( ${NSUBGROUPS}*4 ))
     let annotationstop=$NF-6-$SUBGROUPCOLUMNS
+    echo "annotationstop: $annotationstop"
     
     echo "${tableheader[@]}" | tr ' ' '\t' > ${finalOutput}_RESULTS.tsv
         
